-- 프로즌 데이트 초기 데이터 시딩 (56개 고객처)
-- 실행 전 add_frozen_date_settings.sql 적용 필요

INSERT INTO frozen_date_settings (category, grade, country, customer_name, customer_product_weeks, customer_product_weekday, customer_material_weeks, customer_material_weekday, hq_product_weeks, hq_product_weekday, hq_material_weeks, hq_material_weekday, note) VALUES
('법인', 'D', '미국', '미국(미국동부법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'A', '미국', '미국(미국법인)', 4, 'MON', 3, 'MON', 4, 'FRI', 3, 'FRI', NULL),
('법인', 'B', '멕시코', '멕시코(멕시코법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'A', '중국', '중국(중국법인)', 4, 'MON', 3, 'MON', 4, 'FRI', 3, 'FRI', NULL),
('법인', 'A', '일본', '일본(일본법인)', 4, 'MON', 3, 'MON', 4, 'FRI', 3, 'FRI', NULL),
('법인', 'A', '네덜란드', '네덜란드(유럽법인)', 4, 'MON', 3, 'MON', 4, 'FRI', 3, 'FRI', NULL),
('법인', 'C', '인도', '인도(인도법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'D', '베트남', '베트남(베트남법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'A', '중국', '중국(중국법인_생산)', 4, 'MON', 3, 'MON', 4, 'FRI', 3, 'FRI', '*별도의 프로즌 기준은 없으나, 6~8주 후 출고라 제품 PO와 준비 기간이 비슷함. 따라서, 중국법인과 동일한 프로즌 기준으로 기입함'),
('법인', 'B', '호주', '호주(호주법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'D', '말레이시아', '말레이시아(아시아법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('법인', 'D', '튀르키예', '튀르키예(튀르키예법인)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', '과테말라', '과테말라(Compania de Equipo Medico-Hospitalario, S.A)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'B', '사우디아라비아', '사우디아라비아(Delta Marketing)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', '홍콩', '홍콩(Pro-Med)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '미얀마', '미얀마', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '이라크', '이라크(Eblal Scientific Bureau)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '도미니카공화국', '도미니카공화국(Out Fitness)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'B', '브라질', '브라질(Ottoboni Ltda.)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', '우크라이나', '우크라이나(Aesthetic Medicine Staff Assistance Department LLC)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '아르헨티나', '아르헨티나(Cala Med Argentina SRL)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '캄보디아', '캄보디아(Medilite Pharma)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '아제르바이잔', '아제르바이잔(Mesa Group LLC)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '레바논', '레바논(AlphaPro)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'D', '태국', '태국(InBody Thailand Co., Ltd.)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', 'UAE', 'UAE(Chemsign General Trading LLC)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '요르단', '요르단(Arab Engineers)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '이스라엘', '이스라엘(Energym BashGal)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '볼리비아', '볼리비아(Salur S.R.L)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'D', '인도네시아', '인도네시아(PT. InBody Global Healthcare)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'D', '필리핀', '필리핀(B.Braun Philippines)', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', '러시아/카자흐스탄/우즈베키스탄', '주식회사 이언임페리얼', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '대만', '대만(KOLY)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', 'UAE', 'UAE(SPEC BRITE GENERAL TRADING LLC)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '리비아', '리비아(Arab Engineers)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '페루', '페루(JP REHAB)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '필리핀', '주식회사 인바디글로벌헬스케어', 3, 'MON', 3, 'MON', 3, 'FRI', 3, 'FRI', NULL),
('대리점', 'E', '터키', '터키(Suar Medical)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '팔레스타인', '팔레스타인(Curatek)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '파키스탄', '파키스탄(Aair Medicals)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '우간다', '우간다(End-user)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '몽골', '몽골(ANDROMEDA LLC)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('대리점', 'E', '미얀마', '미얀마(Komyall)', 1, 'MON', 1, 'MON', 1, 'FRI', 1, 'FRI', NULL),
('법인', NULL, '한국', '주식회사 인바디헬스케어', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '*헬스케어>본사 발주 시의 프로즌 확인 필요'),
('법인', NULL, '한국', '인바디 본사', 2, NULL, 2, NULL, 2, NULL, 2, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 강북지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 남부지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 대전지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 부산지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 대구지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 서부지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 강남지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 강서지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 광주지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 중부지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL),
('지사', NULL, '한국', '국내_인바디 강원지사', 1, NULL, 1, NULL, 1, NULL, 1, NULL, NULL)
ON CONFLICT (customer_name) DO NOTHING;
